import type { Metadata } from "next";
import { LegalShell } from "@/components/legal-shell";
import { LEGAL_UPDATED_LABEL } from "@/lib/legal";

export const metadata: Metadata = { title: "Dzieci i AI — egzaminio", description: "Proste zasady bezpiecznego korzystania z nauczyciela AI przez uczniów.", robots: { index: false, follow: false } };

export default function ChildSafetyPage() {
  return (
    <LegalShell currentPath="/bezpieczenstwo-dzieci-ai" title="Dzieci i nauczyciel AI" description={`Najważniejsze zasady prostym językiem · ${LEGAL_UPDATED_LABEL}`} kicker="Dla ucznia i rodzica">
      <div className="legal-callout-grid"><div><b>AI to nie człowiek</b><p>Odpowiedź powstaje automatycznie i może zawierać błąd.</p></div><div><b>Nie wpisuj sekretów</b><p>Bez PESEL-u, adresu, haseł, zdrowia ani cudzych danych.</p></div><div><b>Sprawdzaj ważne rzeczy</b><p>Zapytaj nauczyciela lub porównaj z oficjalnym materiałem.</p></div></div>
      <section className="legal-section"><h2>Co robi nauczyciel AI</h2><p>Pomaga zrozumieć zadanie: może podzielić je na kroki, przypomnieć wzór albo podać prostszy przykład. Nie jest człowiekiem, nie zna Cię tak jak nauczyciel i czasem pewnie brzmi, mimo że się myli. Zgłoś odpowiedź, która wygląda źle lub jest niemiła.</p></section>
      <section className="legal-section"><h2>Zasady dla ucznia</h2><ol><li>Pytaj o zadanie i tok rozumowania, ale nie wklejaj danych swoich ani innych osób.</li><li>Nie traktuj odpowiedzi AI jak oficjalnego klucza ani polecenia nauczyciela.</li><li>Jeśli odpowiedź dotyczy zdrowia, bezpieczeństwa, przemocy lub czegoś, co Cię martwi — przerwij i porozmawiaj z zaufanym dorosłym.</li><li>Nie używaj serwisu do oszukiwania na sprawdzianie. Celem jest zrozumienie, nie gotowiec.</li><li>Możesz poprosić o usunięcie konta i danych przez rodzica lub pisząc na kontakt@egzaminio.io.</li></ol></section>
      <section className="legal-section"><h2>Informacje dla rodzica</h2><ul><li>Konto dziecka pozostaje zablokowane, dopóki zalogowany rodzic używający wskazanego adresu e-mail nie zatwierdzi prośby w swoim panelu.</li><li>Po połączeniu kont i aktywacji Pakietu Plus rodzic zobaczy postęp, regularność i liczbę zakończonych pytań do AI. Prywatna treść rozmów nie jest wyświetlana.</li><li>AI nie ocenia formalnie ucznia, nie decyduje o przyjęciu do szkoły i nie gwarantuje wyniku.</li><li>Dzieci nie otrzymują reklam opartych na profilowaniu ani komunikatów wywierających presję na zakup.</li><li>Rodzic może wycofać zgodę, odłączyć konto i skorzystać z praw opisanych w polityce prywatności.</li></ul></section>
      <section className="legal-section"><h2>Jak projektujemy bezpieczeństwo</h2><p>Domyślne ustawienia minimalizują dane, chronią role kont i nie wykorzystują rozmów dzieci do marketingowego profilowania. Opcjonalny Google Analytics nie uruchamia się przed zgodą i nigdy nie otrzymuje roli dziecko/rodzic, treści zadań, odpowiedzi, wyników, postępu ani rozmów AI. Odmowa analityki nie ogranicza nauki.</p><p>AI otrzymuje wyłącznie treść bieżącego zadania, zatwierdzone opracowanie i rozmowę o tym zadaniu — bez e-maila, profilu i postępów. Wiadomości zawierające oczywiste dane kontaktowe lub treści alarmowe są zatrzymywane przed wysłaniem do modelu. Limity pytań są sprawdzane na serwerze.</p><p>Przed publicznym startem zostaną wykonane testy filtrów, scenariuszy samouszkodzeń, przemocy, treści seksualnych, ujawniania danych i prompt injection oraz ustalona ścieżka szybkiej eskalacji zgłoszeń do człowieka. Zgłoszenia: <a href="mailto:kontakt@egzaminio.io?subject=Bezpieczenstwo%20dziecka%20lub%20blad%20AI">kontakt@egzaminio.io</a>. Wiadomość powinna zawierać opis i identyfikator zadania, ale nie dane wrażliwe dziecka.</p></section>
      <section className="legal-section legal-source-note"><h2>Oficjalne źródła</h2><p><a href="https://uodo.gov.pl/pl/493/2261" target="_blank" rel="noreferrer">UODO o prawach dzieci</a>, <a href="https://digital-strategy.ec.europa.eu/en/faqs/digital-services-act-questions-and-answers" target="_blank" rel="noreferrer">Komisja Europejska o ochronie małoletnich online</a> i <a href="https://digital-strategy.ec.europa.eu/en/policies/guidelines-transparency-ai-generated-content" target="_blank" rel="noreferrer">wymogi przejrzystości AI</a>.</p></section>
    </LegalShell>
  );
}
