import type { Metadata } from "next";
import { LegalShell } from "@/components/legal-shell";
import { LEGAL_UPDATED_LABEL } from "@/lib/legal";

export const metadata: Metadata = { title: "Regulamin — egzaminio", description: "Zasady korzystania z serwisu edukacyjnego egzaminio.", robots: { index: false, follow: false } };

export default function TermsPage() {
  return (
    <LegalShell currentPath="/regulamin" title="Regulamin egzaminio" description={`Wersja robocza · ostatnia aktualizacja: ${LEGAL_UPDATED_LABEL}`}>
      <div className="legal-alert legal-alert-critical"><b>Dane usługodawcy do uzupełnienia</b><p>Usługodawca: <mark>[NAZWA / IMIĘ I NAZWISKO, FORMA PRAWNA, ADRES, KRAJ, NIP/REGON LUB INNY NUMER REJESTROWY]</mark>, e-mail: <a href="mailto:kontakt@egzamin.io">kontakt@egzamin.io</a>. Regulamin wymaga końcowej kontroli po ustaleniu płatności, jurysdykcji operatora i modelu zgody rodzica.</p></div>

      <section className="legal-section"><h2>1. Zakres i definicje</h2><p>Regulamin określa zasady świadczenia drogą elektroniczną usług w serwisie egzaminio. <b>Użytkownik</b> to osoba korzystająca z serwisu. <b>Uczeń</b> to użytkownik przygotowujący się do egzaminu ósmoklasisty. <b>Opiekun</b> to rodzic lub inny przedstawiciel ustawowy. <b>Nauczyciel AI</b> to system sztucznej inteligencji, który generuje wskazówki i wyjaśnienia, a nie człowiek.</p></section>

      <section className="legal-section"><h2>2. Usługi i wymagania techniczne</h2><p>egzaminio udostępnia w szczególności:</p><ul><li>konto ucznia, rodzica, nauczyciela lub administratora,</li><li>ćwiczenia i materiały przygotowujące do egzaminu,</li><li>zapisywanie wyników i postępów,</li><li>generowane przez AI wyjaśnienia i możliwość dalszych pytań,</li><li>raporty oraz powiązania kont, gdy dana funkcja jest dostępna,</li><li>plan bezpłatny, a po uruchomieniu także plan płatny.</li></ul><p>Potrzebne są: aktualna przeglądarka obsługująca JavaScript i local storage, połączenie z internetem oraz działający adres e-mail albo konto Google/Facebook. Użytkownik powinien chronić urządzenie i dane logowania. Koszt internetu ponosi według umowy ze swoim operatorem.</p></section>

      <section className="legal-section"><h2>3. Zawarcie umowy i konto</h2><ol><li>Umowa o konto zostaje zawarta po przesłaniu rejestracji i potwierdzeniu adresu e-mail albo po skutecznym logowaniu społecznościowym oraz akceptacji regulaminu.</li><li>Użytkownik podaje dane prawdziwe i aktualne. Jedna osoba nie powinna podszywać się pod inną ani udostępniać konta poza funkcjami przewidzianymi w serwisie.</li><li>Rola administratora nie jest dostępna w samodzielnej rejestracji. Uprawnienia zależą od wybranej roli i są chronione po stronie bazy danych.</li><li>Konto można zakończyć w ustawieniach <mark>[DODAJ PRZYCISK PRZED STARTEM]</mark> albo pisząc na kontakt@egzamin.io.</li></ol></section>

      <section className="legal-section"><h2>4. Uczniowie niepełnoletni</h2><p>Konto ucznia wymaga udziału opiekuna w zakresie wymaganym przez prawo i przyjęty model usługi. Uczeń podaje odrębny e-mail opiekuna, a konto pozostaje zablokowane do chwili zatwierdzenia prośby przez zalogowane konto rodzica używające tego adresu. Opiekun odpowiada za prawdziwość potwierdzenia i może cofnąć zgodę. Ostateczny poziom weryfikacji zostanie potwierdzony w konsultacji prawnej przed publicznym startem.</p><p>Serwis nie może być używany do zastąpienia szkoły, formalnego oceniania ucznia ani podejmowania decyzji o przyjęciu do szkoły. Zasady w prostszym języku są na stronie <a href="/bezpieczenstwo-dzieci-ai">Dzieci i AI</a>.</p></section>

      <section className="legal-section"><h2>5. Dozwolone korzystanie</h2><p>Nie wolno:</p><ul><li>przekazywać treści bezprawnych, krzywdzących, naruszających prywatność lub prawa autorskie,</li><li>obchodzić limitów, zabezpieczeń, ról i kontroli dostępu,</li><li>automatycznie pobierać bazy zadań, odsprzedawać konta lub udostępniać treści poza dozwolonym użytkiem,</li><li>wprowadzać złośliwego kodu, zakłócać usługi ani testować zabezpieczeń bez pisemnej zgody,</li><li>wpisywać do AI cudzych danych osobowych, danych medycznych, haseł, numerów dokumentów lub innych informacji wrażliwych.</li></ul><p>Możemy ograniczyć funkcję lub konto, jeśli jest to proporcjonalnie potrzebne dla bezpieczeństwa lub naruszenie jest istotne. Jeżeli sytuacja pozwala, wyjaśnimy przyczynę i umożliwimy kontakt lub odwołanie.</p></section>

      <section className="legal-section"><h2>6. Nauczyciel AI i materiały edukacyjne</h2><p>Odpowiedzi AI są generowane automatycznie i mogą być niepełne lub błędne. Nauczyciel AI ma pomagać zrozumieć tok rozumowania, ale nie stanowi oficjalnego klucza odpowiedzi, profesjonalnej porady ani gwarancji wyniku. Użytkownik powinien weryfikować ważne informacje z nauczycielem i materiałem źródłowym. Błędy można zgłaszać na kontakt@egzamin.io.</p><p>Materiały pochodzące z arkuszy publicznych będą oznaczane źródłem, rokiem i przedmiotem. egzaminio jest niezależnym projektem i nie jest powiązane z Centralną Komisją Egzaminacyjną. <mark>Przed komercyjnym udostępnieniem każdego zbioru trzeba potwierdzić zakres licencji lub dozwolonego wykorzystania materiału, grafiki i klucza odpowiedzi.</mark></p></section>

      <section className="legal-section"><h2>7. Plan bezpłatny i przyszłe płatności</h2><p>Obecny MVP oferuje bezpłatny start z limitami opisanymi w serwisie. Plan Plus jest planowany w cenie 119 zł za 12 miesięcy dostępu. Nie można go jeszcze kupić — przed uruchomieniem płatności pokażemy ostateczny zakres planu, całkowitą cenę, zasady odnowienia, czas trwania i sposób rezygnacji. Przycisk zakupu będzie jednoznacznie informował o obowiązku zapłaty.</p><p>Jeżeli usługa cyfrowa ma rozpocząć się przed upływem 14 dni, poprosimy konsumenta o odpowiednie wyraźne żądanie. W przypadku treści cyfrowej niedostarczanej na nośniku utrata prawa odstąpienia może nastąpić tylko po spełnieniu wszystkich warunków ustawowych, w tym uprzedniej wyraźnej zgody, potwierdzenia wiedzy o utracie prawa i przekazania potwierdzenia umowy. Szczegóły: <a href="/odstapienie-od-umowy">odstąpienie od umowy</a>.</p></section>

      <section className="legal-section"><h2>8. Reklamacje</h2><p>Reklamację można złożyć na kontakt@egzamin.io, podając adres konta, opis problemu, oczekiwane rozwiązanie i — bez danych wrażliwych — informacje potrzebne do odtworzenia błędu. Potwierdzimy otrzymanie i odpowiemy w ciągu 14 dni. Prawa z tytułu niezgodności usługi cyfrowej z umową ani inne bezwzględnie obowiązujące prawa konsumenta nie są ograniczone tym regulaminem.</p></section>

      <section className="legal-section"><h2>9. Dostępność, odpowiedzialność i zakończenie</h2><p>Dążymy do ciągłej dostępności, ale mogą wystąpić przerwy na utrzymanie, awarie lub zdarzenia poza rozsądną kontrolą. O planowanej dłuższej przerwie poinformujemy, gdy to możliwe. Nie wyłączamy odpowiedzialności, której nie można wyłączyć wobec konsumenta, w szczególności za umyślne działanie, rażące niedbalstwo, szkodę na osobie ani obowiązki wynikające z przepisów o usługach cyfrowych.</p><p>Użytkownik może wypowiedzieć bezpłatną umowę w każdej chwili przez usunięcie konta. Usługodawca może zakończyć usługę z ważnej przyczyny, z rozsądnym wyprzedzeniem, chyba że natychmiastowe działanie jest konieczne ze względów bezpieczeństwa lub prawa.</p></section>

      <section className="legal-section"><h2>10. Zmiany i postanowienia końcowe</h2><p>Regulamin może się zmienić z powodu prawa, bezpieczeństwa, zmian technicznych lub rozwoju usługi. O zmianie dotyczącej istniejącej umowy poinformujemy na trwałym nośniku z odpowiednim wyprzedzeniem i wskażemy prawo do zakończenia umowy, gdy jest wymagane. Właściwe jest prawo <mark>[UZUPEŁNIJ PO USTALENIU SIEDZIBY]</mark>, bez pozbawiania konsumenta ochrony przepisów bezwzględnie obowiązujących w jego miejscu zwykłego pobytu.</p><p>Konsument może skorzystać z pomocy miejskiego lub powiatowego rzecznika konsumentów oraz właściwego podmiotu pozasądowego rozwiązywania sporów. Aktualne informacje publikuje <a href="https://polubowne.uokik.gov.pl/" target="_blank" rel="noreferrer">UOKiK</a>.</p></section>

      <section className="legal-section legal-source-note"><h2>Oficjalne źródła</h2><p><a href="https://eli.gov.pl/api/acts/DU/2024/1513/text.html" target="_blank" rel="noreferrer">Ustawa o świadczeniu usług drogą elektroniczną</a> i <a href="https://prawakonsumenta.uokik.gov.pl/prawo-do-informacji/sprzedaz-poza-lokalem-i-na-odleglosc/" target="_blank" rel="noreferrer">informacje UOKiK dla umów na odległość</a>.</p></section>
    </LegalShell>
  );
}
