/* eslint-disable @next/next/no-html-link-for-pages -- Full-page anchors avoid a Vinext production navigation failure. */

import type { Metadata } from "next";
import { LegalShell } from "@/components/legal-shell";
import { LEGAL_UPDATED_LABEL } from "@/lib/legal";

export const metadata: Metadata = { title: "Regulamin — egzaminio", description: "Zasady korzystania z serwisu edukacyjnego egzaminio.", robots: { index: false, follow: false } };

export default function TermsPage() {
  return (
    <LegalShell currentPath="/regulamin" title="Regulamin egzaminio" description={`Wersja robocza · ostatnia aktualizacja: ${LEGAL_UPDATED_LABEL}`}>
      <div className="legal-alert legal-alert-critical"><b>Dane usługodawcy i klasyfikacja świadczenia do zatwierdzenia</b><p>Usługodawca: <mark>[NAZWA / IMIĘ I NAZWISKO, FORMA PRAWNA, ADRES, KRAJ, NIP/REGON LUB INNY NUMER REJESTROWY]</mark>, e-mail: <a href="mailto:kontakt@egzamin.io">kontakt@egzamin.io</a>. Stripe Checkout i opisany niżej proces są wdrożone technicznie, ale przed włączeniem sprzedaży prawnik musi zatwierdzić dane sprzedawcy, podatki, potwierdzenie umowy na trwałym nośniku oraz kwalifikację pakietu jako usługi albo treści cyfrowej.</p></div>

      <section className="legal-section"><h2>1. Zakres i definicje</h2><p>Regulamin określa zasady świadczenia drogą elektroniczną usług w serwisie egzaminio. <b>Użytkownik</b> to osoba korzystająca z serwisu. <b>Uczeń</b> to użytkownik przygotowujący się do egzaminu ósmoklasisty. <b>Opiekun</b> to rodzic lub inny przedstawiciel ustawowy. <b>Nauczyciel AI</b> to system sztucznej inteligencji, który generuje wskazówki i wyjaśnienia, a nie człowiek.</p></section>

      <section className="legal-section"><h2>2. Usługi i wymagania techniczne</h2><p>egzaminio udostępnia w szczególności:</p><ul><li>konto ucznia, rodzica, nauczyciela lub administratora,</li><li>ćwiczenia i materiały przygotowujące do egzaminu,</li><li>zapisywanie wyników i postępów,</li><li>generowane przez AI wyjaśnienia i możliwość dalszych pytań,</li><li>raporty oraz powiązania kont, gdy dana funkcja jest dostępna,</li><li>plan bezpłatny, a po uruchomieniu także plan płatny.</li></ul><p>Potrzebne są: aktualna przeglądarka obsługująca JavaScript i local storage, połączenie z internetem oraz działający adres e-mail albo konto Google. Użytkownik powinien chronić urządzenie i dane logowania. Koszt internetu ponosi według umowy ze swoim operatorem.</p><p>Opcjonalna analityka Google Analytics służy ulepszaniu serwisu i działa wyłącznie po zgodzie. Odmowa lub wycofanie zgody nie zmienia zakresu umowy, dostępu do konta ani ćwiczeń.</p></section>

      <section className="legal-section"><h2>3. Zawarcie umowy i konto</h2><ol><li>Umowa o konto zostaje zawarta po przesłaniu rejestracji i potwierdzeniu adresu e-mail albo po skutecznym logowaniu społecznościowym oraz akceptacji regulaminu.</li><li>Użytkownik podaje dane prawdziwe i aktualne. Jedna osoba nie powinna podszywać się pod inną ani udostępniać konta poza funkcjami przewidzianymi w serwisie.</li><li>Rola administratora nie jest dostępna w samodzielnej rejestracji. Uprawnienia zależą od wybranej roli i są chronione po stronie bazy danych.</li><li>Konto można zakończyć w ustawieniach <mark>[DODAJ PRZYCISK PRZED STARTEM]</mark> albo pisząc na kontakt@egzamin.io.</li></ol></section>

      <section className="legal-section"><h2>4. Uczniowie niepełnoletni</h2><p>Konto ucznia wymaga udziału opiekuna w zakresie wymaganym przez prawo i przyjęty model usługi. Uczeń podaje odrębny e-mail opiekuna, a konto pozostaje zablokowane do chwili zatwierdzenia prośby przez zalogowane konto rodzica używające tego adresu. Opiekun odpowiada za prawdziwość potwierdzenia i może cofnąć zgodę. Ostateczny poziom weryfikacji zostanie potwierdzony w konsultacji prawnej przed publicznym startem.</p><p>Serwis nie może być używany do zastąpienia szkoły, formalnego oceniania ucznia ani podejmowania decyzji o przyjęciu do szkoły. Zasady w prostszym języku są na stronie <a href="/bezpieczenstwo-dzieci-ai">Dzieci i AI</a>.</p></section>

      <section className="legal-section"><h2>5. Dozwolone korzystanie</h2><p>Nie wolno:</p><ul><li>przekazywać treści bezprawnych, krzywdzących, naruszających prywatność lub prawa autorskie,</li><li>obchodzić limitów, zabezpieczeń, ról i kontroli dostępu,</li><li>automatycznie pobierać bazy zadań, odsprzedawać konta lub udostępniać treści poza dozwolonym użytkiem,</li><li>wprowadzać złośliwego kodu, zakłócać usługi ani testować zabezpieczeń bez pisemnej zgody,</li><li>wpisywać do AI cudzych danych osobowych, danych medycznych, haseł, numerów dokumentów lub innych informacji wrażliwych.</li></ul><p>Możemy ograniczyć funkcję lub konto, jeśli jest to proporcjonalnie potrzebne dla bezpieczeństwa lub naruszenie jest istotne. Jeżeli sytuacja pozwala, wyjaśnimy przyczynę i umożliwimy kontakt lub odwołanie.</p></section>

      <section className="legal-section"><h2>6. Nauczyciel AI i materiały edukacyjne</h2><p>Odpowiedzi AI są generowane automatycznie i mogą być niepełne lub błędne. Nauczyciel AI ma pomagać zrozumieć tok rozumowania, ale nie stanowi oficjalnego klucza odpowiedzi, profesjonalnej porady ani gwarancji wyniku. Użytkownik powinien weryfikować ważne informacje z nauczycielem i materiałem źródłowym. Błędy można zgłaszać na kontakt@egzamin.io.</p><p>Materiały pochodzące z arkuszy publicznych będą oznaczane źródłem, rokiem i przedmiotem. egzaminio jest niezależnym projektem i nie jest powiązane z Centralną Komisją Egzaminacyjną. <mark>Przed komercyjnym udostępnieniem każdego zbioru trzeba potwierdzić zakres licencji lub dozwolonego wykorzystania materiału, grafiki i klucza odpowiedzi.</mark></p></section>

      <section className="legal-section"><h2>7. Wersja bezpłatna i Pakiet Plus</h2><p>Wersja bezpłatna zapewnia dostęp do wszystkich opublikowanych arkuszy CKE oraz pozwala interaktywnie sprawdzić odpowiedzi do 15 różnych pytań w ciągu dnia. Dzień rozliczamy według czasu polskiego. Ponowne sprawdzenie tego samego pytania tego samego dnia nie zmniejsza limitu. W wersji bezpłatnej nie udostępniamy trwałego śledzenia postępów ani Nauczyciela AI.</p><p>Pakiet Plus odblokowuje interaktywne rozwiązywanie bez limitu, trwały zapis i analizę postępów, powtórki oraz Nauczyciela AI z limitem do 50 udanych pytań dziennie. Pakiet kosztuje <b>149 zł brutto</b> i jest kupowany przez zalogowane konto rodzica dla wskazanego, połączonego konta ucznia. Jest to płatność jednorazowa — bez abonamentu i automatycznego odnowienia. Przed złożeniem zamówienia pokazujemy pełną cenę, zakres pakietu i dokładną datę końca dostępu. Data ta zostaje zapisana przy zamówieniu i nie zmienia się wskutek późniejszej zmiany oferty.</p><p>Zamówienie zostaje złożone po zaznaczeniu wymaganych potwierdzeń i użyciu przycisku „Zamawiam pakiet Plus — płacę 149 zł”. Płatność obsługuje hostowana strona Stripe. Dostępu nie aktywuje samo przekierowanie po płatności: następuje to dopiero po potwierdzeniu otrzymanym i zweryfikowanym od Stripe. Status, zwroty i dostępne dokumenty płatności są widoczne w panelu rodzica.</p><p>Jeżeli świadczenie ma rozpocząć się przed upływem 14 dni, prosimy o wyraźne żądanie rozpoczęcia go od razu. Skutek odstąpienia i ewentualne proporcjonalne rozliczenie zależą od rodzaju świadczenia, zakresu wykonania i przepisów bezwzględnie obowiązujących; samo zaznaczenie pola nie pozbawia automatycznie prawa odstąpienia. Szczegóły: <a href="/odstapienie-od-umowy">odstąpienie od umowy</a>.</p><p>Stripe może wysłać potwierdzenie i dokument na adres e-mail rodzica. Obowiązkowe informacje o umowie muszą zostać przekazane na trwałym nośniku. <mark>Przed startem produkcyjnym trzeba przetestować treść wiadomości Stripe i — jeżeli nie zawiera kompletu wymaganych informacji — uruchomić osobną wiadomość transakcyjną egzaminio.</mark></p></section>

      <section className="legal-section"><h2>8. Reklamacje, płatności i zwroty</h2><p>Reklamację, pytanie o płatność albo prośbę o zwrot można złożyć na kontakt@egzamin.io, podając adres konta rodzica, datę zakupu, opis problemu i oczekiwane rozwiązanie. Nie wysyłaj danych karty. Potwierdzimy otrzymanie i odpowiemy w ciągu 14 dni. Zwrot jest kierowany przez Stripe na pierwotną metodę płatności; czas zaksięgowania zależy również od banku. Po pełnym zwrocie dostęp wynikający z danego zamówienia zostanie wyłączony, o ile nie istnieje inne ważne uprawnienie. Prawa z tytułu niezgodności usługi cyfrowej z umową ani inne bezwzględnie obowiązujące prawa konsumenta nie są ograniczone tym regulaminem.</p></section>

      <section className="legal-section"><h2>9. Dostępność, odpowiedzialność i zakończenie</h2><p>Dążymy do ciągłej dostępności, ale mogą wystąpić przerwy na utrzymanie, awarie lub zdarzenia poza rozsądną kontrolą. O planowanej dłuższej przerwie poinformujemy, gdy to możliwe. Nie wyłączamy odpowiedzialności, której nie można wyłączyć wobec konsumenta, w szczególności za umyślne działanie, rażące niedbalstwo, szkodę na osobie ani obowiązki wynikające z przepisów o usługach cyfrowych.</p><p>Użytkownik może wypowiedzieć bezpłatną umowę w każdej chwili przez usunięcie konta. Usługodawca może zakończyć usługę z ważnej przyczyny, z rozsądnym wyprzedzeniem, chyba że natychmiastowe działanie jest konieczne ze względów bezpieczeństwa lub prawa.</p></section>

      <section className="legal-section"><h2>10. Zmiany i postanowienia końcowe</h2><p>Regulamin może się zmienić z powodu prawa, bezpieczeństwa, zmian technicznych lub rozwoju usługi. O zmianie dotyczącej istniejącej umowy poinformujemy na trwałym nośniku z odpowiednim wyprzedzeniem i wskażemy prawo do zakończenia umowy, gdy jest wymagane. Właściwe jest prawo <mark>[UZUPEŁNIJ PO USTALENIU SIEDZIBY]</mark>, bez pozbawiania konsumenta ochrony przepisów bezwzględnie obowiązujących w jego miejscu zwykłego pobytu.</p><p>Konsument może skorzystać z pomocy miejskiego lub powiatowego rzecznika konsumentów oraz właściwego podmiotu pozasądowego rozwiązywania sporów. Aktualne informacje publikuje <a href="https://polubowne.uokik.gov.pl/" target="_blank" rel="noreferrer">UOKiK</a>.</p></section>

      <section className="legal-section legal-source-note"><h2>Oficjalne źródła</h2><p><a href="https://eli.gov.pl/api/acts/DU/2024/1513/text.html" target="_blank" rel="noreferrer">Ustawa o świadczeniu usług drogą elektroniczną</a> i <a href="https://prawakonsumenta.uokik.gov.pl/prawo-do-informacji/sprzedaz-poza-lokalem-i-na-odleglosc/" target="_blank" rel="noreferrer">informacje UOKiK dla umów na odległość</a>.</p></section>
    </LegalShell>
  );
}
