import type { Metadata } from "next";
import { LegalShell } from "@/components/legal-shell";
import { LEGAL_UPDATED_LABEL } from "@/lib/legal";

export const metadata: Metadata = { title: "Polityka cookies — egzaminio", description: "Cookies, pamięć urządzenia i opcjonalna analityka Google Analytics w egzaminio.", robots: { index: false, follow: false } };

export default function CookiesPage() {
  return <LegalShell currentPath="/polityka-cookies" title="Cookies i pamięć urządzenia" description={`Wersja robocza · ostatnia aktualizacja: ${LEGAL_UPDATED_LABEL}`}>
    <div className="legal-alert"><b>Google Analytics wyłącznie po zgodzie</b><p>Stosujemy podstawowy Consent Mode. Przed zgodą albo po odmowie skrypt Google nie jest pobierany, żaden pomiar nie jest wysyłany do Google i cookies analityczne nie są ustawiane. Odmowa nie ogranicza działania konta ani ćwiczeń.</p></div>
    <section className="legal-section"><h2>1. Jak działa wybór</h2><p>Przy pierwszej wizycie można zaakceptować analitykę, odrzucić ją albo otworzyć ustawienia. Wybór wraz z wersją komunikatu i czasem zapisujemy wyłącznie na urządzeniu, w kluczu <code>egzaminio:privacy-consent</code>, przez maksymalnie 180 dni. Nie łączymy tego zapisu z kontem ani profilem dziecka. Po wygaśnięciu ponownie pytamy o decyzję.</p></section>
    <section className="legal-section"><h2>2. Faktycznie używane technologie</h2><div className="legal-table-wrap"><table><thead><tr><th>Nazwa / kategoria</th><th>Dostawca i cel</th><th>Okres</th><th>Kiedy działa</th></tr></thead><tbody>
      <tr><td>Pamięć sesji Supabase Auth — niezbędna</td><td>Supabase: logowanie, odświeżenie sesji i wylogowanie. Nazwa klucza zależy od identyfikatora projektu.</td><td>Do wylogowania, wygaśnięcia sesji albo usunięcia danych witryny</td><td>Gdy użytkownik korzysta z konta; bez osobnej zgody</td></tr>
      <tr><td><code>egzaminio-theme</code> — opcjonalna preferencja</td><td>egzaminio: zapamiętanie wyboru systemowego, jasnego lub ciemnego wyglądu. Bez ręcznej zmiany stosujemy ustawienie systemowe urządzenia.</td><td>Do zmiany ustawienia lub usunięcia danych witryny</td><td>Po zmianie wyglądu w ustawieniach aplikacji</td></tr>
      <tr><td><code>egzaminio:privacy-consent</code> — niezbędna preferencja</td><td>egzaminio: zapamiętanie wersji, wyboru i czasu zgody bez powiązania z profilem.</td><td>Maksymalnie 180 dni</td><td>Po podjęciu decyzji</td></tr>
      <tr><td><code>_ga</code> i <code>_ga_&lt;measurement-id&gt;</code> — analityczne</td><td>Google Analytics 4 / Google Ireland Limited: rozróżnianie urządzeń i sesji oraz minimalny pomiar lejka MVP.</td><td>Maksymalnie 90 dni; okres nie jest odnawiany przy kolejnych wizytach</td><td>Dopiero po zgodzie na analitykę</td></tr>
    </tbody></table></div><p>Nie używamy cookies reklamowych, remarketingu ani personalizacji reklam. Google Signals, funkcje reklamowe, połączenie z Google Ads i rozszerzony pomiar powinny pozostać wyłączone.</p></section>
    <section className="legal-section"><h2>3. Co mierzymy</h2><p>Po zgodzie wysyłamy wyłącznie nazwę jednego z zatwierdzonych zdarzeń: odsłonę, rozpoczęcie lub zakończenie rejestracji, zakończenie logowania, rozpoczęcie ćwiczeń, sprawdzenie odpowiedzi oraz wyświetlenie lub kliknięcie pakietu Plus. Adres strony jest pozbawiany parametrów, fragmentu po znaku <code>#</code>, tokenów i segmentów przypominających identyfikatory.</p><p>Nie przekazujemy do GA e-maila, imienia, identyfikatora konta, roli użytkownika, szkoły, treści zadania, wybranej odpowiedzi, poprawności, wyniku, postępu ani rozmowy z AI. Samo kliknięcie przycisku Google nie uruchamia Google Analytics bez zgody.</p></section>
    <section className="legal-section"><h2>4. Zmiana lub wycofanie zgody</h2><p>Przycisk „Ustawienia prywatności” jest dostępny w dyskretnej sekcji pod treścią każdej strony. Po wycofaniu zgody zatrzymujemy przyszłe pomiary, usuwamy cookies <code>_ga</code> ustawione przez aplikację i przeładowujemy stronę bez taga. Można również usunąć dane witryny w ustawieniach przeglądarki. Wycofanie zgody nie wpływa na zgodność wcześniejszego przetwarzania.</p></section>
    <section className="legal-section legal-source-note"><h2>Oficjalne źródła</h2><p><a href="https://eli.gov.pl/api/acts/DU/2024/1221/text.html" target="_blank" rel="noreferrer">Prawo komunikacji elektronicznej — art. 399</a>, <a href="https://developers.google.com/tag-platform/security/concepts/consent-mode" target="_blank" rel="noreferrer">Google Consent Mode</a>, <a href="https://support.google.com/analytics/answer/11397207" target="_blank" rel="noreferrer">cookies GA4</a> oraz <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noreferrer">jak Google wykorzystuje dane z witryn partnerów</a>.</p></section>
  </LegalShell>;
}
